# Ironhack note - This file is for running in docker compose with prebuilt images
# Use these if you're stuck, or if you want to start slowly migrating from external images into your own.

services:
  worker:
 #  build: ./worker
    image: vijayagagla123/worker:latest
    environment:
      REDIS_HOST: ${REDIS_HOST} 
      REDIS_PORT: ${REDIS_PORT} 
      PG_HOST: ${PG_HOST} 
      DB_HOST: ${DB_HOST} 
      DB_USERNAME: ${DB_USERNAME} 
      DB_PASSWORD: ${DB_PASSWORD} 
      DB_NAME: ${DB_NAME} 
    networks:
      - back-tier

  redis:
    image: redis:alpine
    ports:
    - "6379:6379"
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "5s"

    networks:
      - back-tier

volumes:
  db-data:

networks:
  back-tier: